# Generated by Django 3.2 on 2021-06-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_pat', models.CharField(max_length=20)),
                ('apellido_mat', models.CharField(max_length=20)),
                ('correo_ins', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('correo_per', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('tipo', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='P_M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_mechon', to='perfiles.persona')),
                ('rut_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_padrino', to='perfiles.persona')),
            ],
        ),
    ]
