# Generated by Django 3.2 on 2021-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_m',
            name='estado',
            field=models.IntegerField(choices=[(0, 'pendiente'), (1, 'activo')], default=1),
            preserve_default=False,
        ),
    ]
