# Generated by Django 3.2 on 2021-06-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[(0, 'Padrino'), (1, 'Mechon'), (2, 'Moderador'), (3, 'Super_padrino')], max_length=20),
        ),
    ]
