# Generated by Django 3.2 on 2021-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_p_m_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_m',
            name='fecha_creada',
            field=models.DateField(auto_now=True),
        ),
    ]
