# Generated by Django 3.2 on 2021-06-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_alter_persona_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='descripcion',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
