# Generated by Django 3.2 on 2021-08-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_persona_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
