# Generated by Django 3.2 on 2021-08-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_alter_persona_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='gusto',
            field=models.IntegerField(choices=[(0, 'Videojuegos'), (1, 'Programar'), (2, 'Cocinar'), (3, 'Musica'), (4, 'Rol'), (5, 'Peliculas / Series'), (6, 'Puzzles'), (7, 'Astronomia'), (8, 'Debate'), (9, 'Matematicas')], null=True),
        ),
    ]
