# Generated by Django 3.2 on 2021-10-16 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona_Auth',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('correo_per', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.IntegerField(choices=[(0, 'Padrino'), (1, 'Mechon'), (2, 'Moderador'), (3, 'Super_padrino')])),
                ('gusto', models.IntegerField(choices=[(0, 'Videojuegos'), (1, 'Programar'), (2, 'Cocinar'), (3, 'Musica'), (4, 'Rol'), (5, 'Peliculas / Series'), (6, 'Puzzles'), (7, 'Astronomia'), (8, 'Debate'), (9, 'Matematicas')], null=True)),
                ('carrera', models.IntegerField(choices=[(0, 'Geologia'), (1, 'Ingenieria Civil'), (2, 'Ingenieria Civil en Minas'), (3, 'Ingenieria Civil Industrial'), (4, 'Ingenieria Civil Informatica'), (5, 'Ingenieria en Automatizacion y Robotica'), (6, 'Ingenieria en Computacion e informatica'), (7, 'Ingenieria en Costruccion'), (8, 'Ingenieria en Marina Mercante'), (9, 'Ingenieria Industrial')])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='P_M',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_creada', models.DateField(auto_now_add=True)),
                ('rut_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_mechon', to='perfiles.persona_auth')),
                ('rut_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_padrino', to='perfiles.persona_auth')),
            ],
        ),
    ]
