# Generated by Django 3.2 on 2022-01-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_p_m_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_auth',
            name='interes',
            field=models.IntegerField(choices=[(0, 'Videojuegos'), (1, 'Programar'), (2, 'Cocinar'), (3, 'Musica'), (4, 'Rol'), (5, 'Peliculas / Series'), (6, 'Puzzles'), (7, 'Astronomia'), (8, 'Debate'), (9, 'Matematicas')], null=True),
        ),
    ]
