# Generated by Django 3.2 on 2022-01-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_persona_auth_interes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona_auth',
            name='interes',
        ),
    ]
