# Generated by Django 3.2 on 2022-01-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_archivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='estado',
            field=models.IntegerField(choices=[(0, 'activo'), (1, 'quitado')]),
        ),
    ]
