# Generated by Django 3.2 on 2022-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_auto_20220118_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(default='exde', max_length=100),
            preserve_default=False,
        ),
    ]
