# Generated by Django 3.2 on 2022-01-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_archivo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='subido_por',
            field=models.CharField(default='f.fuentesbaez', max_length=100),
            preserve_default=False,
        ),
    ]
