# Generated by Django 3.2 on 2022-01-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_remove_persona_auth_interes'),
        ('archivos', '0005_archivo_subido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.persona_auth'),
        ),
    ]
