# Generated by Django 3.2 on 2021-10-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_agendada',
            field=models.DateField(),
        ),
    ]
