# Generated by Django 3.2 on 2021-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20211027_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='creada_por',
            field=models.CharField(default='Felipe', max_length=40),
            preserve_default=False,
        ),
    ]
